# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-12 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('image', models.ImageField(default='card_collection/images/card_placeholder.png', upload_to='card_collection/images/cards')),
                ('card_type', models.IntegerField(choices=[(0, 'action'), (1, 'creature'), (2, 'item'), (3, 'support')])),
                ('rarity', models.IntegerField(choices=[(0, 'common'), (1, 'rare'), (2, 'epic'), (3, 'legendary'), (4, 'unique legendary')])),
                ('summon_cost', models.IntegerField(blank=True, null=True)),
                ('soultrap_cost', models.IntegerField(blank=True, null=True)),
                ('magicka_cost', models.IntegerField()),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('mechanics_text', models.TextField()),
                ('flavor_text', models.TextField()),
                ('is_collectible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='card_collection.Card')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('deck_archetype', models.IntegerField(choices=[(0, 'aggro'), (1, 'midrange'), (2, 'control'), (3, 'hybrid')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cards', models.ManyToManyField(to='card_collection.Card')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralEntity',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_attributes',
            field=models.ManyToManyField(to='card_collection.Attribute'),
        ),
        migrations.AddField(
            model_name='card',
            name='attributes',
            field=models.ManyToManyField(to='card_collection.Attribute'),
        ),
        migrations.AddField(
            model_name='card',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_collection.Expansion'),
        ),
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='card_collection.Keyword'),
        ),
        migrations.AddField(
            model_name='card',
            name='races',
            field=models.ManyToManyField(blank=True, to='card_collection.Race'),
        ),
    ]
