# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 15:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='http://elderdecks.com/img/customcards/the_gondolier_by_2-793.png', upload_to='cards')),
                ('summon_cost', models.IntegerField()),
                ('soultrap_cost', models.IntegerField()),
                ('magicka_cost', models.IntegerField()),
                ('attack', models.IntegerField(blank=True, null=True)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('mechanics_text', models.TextField()),
                ('flavor_text', models.TextField()),
                ('is_collectible', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cards', models.IntegerField()),
                ('card', models.ManyToManyField(to='card_collection.Card')),
                ('owner', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeckAuthors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeckContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_cards', models.IntegerField()),
                ('card', models.ManyToManyField(to='card_collection.Card')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralEntity',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='card_collection.GeneralEntity')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.CreateModel(
            name='DeckArchetype',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.CreateModel(
            name='DeckClass',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
                ('attributes', models.ManyToManyField(to='card_collection.Attribute')),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
                ('is_actual', models.BooleanField()),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('generalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card_collection.GeneralEntity')),
            ],
            bases=('card_collection.generalentity',),
        ),
        migrations.AddField(
            model_name='deckcontent',
            name='deck',
            field=models.ManyToManyField(to='card_collection.Deck'),
        ),
        migrations.AddField(
            model_name='deckauthors',
            name='deck',
            field=models.ManyToManyField(to='card_collection.Deck'),
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_archetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_collection.DeckArchetype'),
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_collection.DeckClass'),
        ),
        migrations.AddField(
            model_name='card',
            name='attributes',
            field=models.ManyToManyField(to='card_collection.Attribute'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_collection.CardType'),
        ),
        migrations.AddField(
            model_name='card',
            name='expansion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_collection.Expansion'),
        ),
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='card_collection.Keyword'),
        ),
        migrations.AddField(
            model_name='card',
            name='races',
            field=models.ManyToManyField(blank=True, to='card_collection.Race'),
        ),
        migrations.AddField(
            model_name='card',
            name='rarity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card_collection.Rarity'),
        ),
    ]
