# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='id',
            field=models.AutoField(auto_created=True, default=77, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='deck',
            name='deck_archetype',
            field=models.IntegerField(choices=[(1, 'aggro'), (2, 'midrange'), (3, 'control'), (4, 'hybrid')]),
        ),
    ]
